### ISSUE TITLE
Visiting the website leads to a HuggingFace error page

### ISSUE THREAD

**Issue by AaravMalani** [Ahmet-Dedeler/Chat-With-Youtube_All-In-Hackathon#1]
**To Reproduce the Error:**
- Visit [the website](http://chat-with-youtube.co/)

**Error:** The page immediately 307s to a [HuggingFace space](https://huggingface.co/spaces/chai182/ChatWithYoutube)

![The page](https://github.com/Ahmet-Dedeler/Chat-With-Youtube_All-In-Hackathon/assets/105878671/841f222f-8d14-420e-919a-031837afd1b5)

**Comment by Ahmet-Dedeler** [comment]
Seems like the Space got shut down, restarted it!
